/*
 * Copyright 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.compose.runtime.internal

import androidx.compose.runtime.ComposeCompilerApi

/**
 * Used with decoys to stub the body of the decoy function.
 * Any call to this function at runtime indicates compiler error, as all calls to decoys
 * should be compiled out.
 */
@Suppress("unused")
@ComposeCompilerApi
fun illegalDecoyCallException(fName: String): Nothing =
    throw IllegalStateException(
        "Function $fName should have been replaced by compiler."
    )

/**
 * With decoys enabled, indicates original composable function that was stubbed by compiler
 * plugin. Provides metadata to link it with the implementation function
 * generated by compiler.
 *
 * @param targetName The name of the actual composable function
 * @param signature Serialized signature of the actual composable function
 */
@Suppress("unused")
@ComposeCompilerApi
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CONSTRUCTOR)
annotation class Decoy(val targetName: String, vararg val signature: String)

/**
 * With decoys enabled, indicates composable implementation function created by compiler plugin.
 *
 * @param targetName The name of the implementation function used to locate it. In most cases it
 * matches the name of the function itself.
 */
@Suppress("unused")
@ComposeCompilerApi
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.CONSTRUCTOR)
annotation class DecoyImplementation(val targetName: String)
